# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    tags:
      - osusergo
      - netgo
      - static_build
      - feature
archives:
  - replacements:
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "echo-{{.Commit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - image_templates:
      - "mynuolr/echo:{{ .Version }}-amd64"
    use_buildx: true
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "mynuolr/echo:{{ .Version }}-arm64v8"
    use_buildx: true
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: mynuolr/echo:{{ .Version }}
    image_templates:
      - mynuolr/echo:{{ .Version }}-amd64
      - mynuolr/echo:{{ .Version }}-arm64v8
  - name_template: mynuolr/echo:latest
    image_templates:
      - mynuolr/echo:{{ .Version }}
